### ISSUE TITLE
error unable to load package

### ISSUE THREAD

**Issue by trim21** [masaushi/accessory#25]
I encounter a error when generating my package `accessory: packages.go:1214: Unexpected package creation during export data loading`

it failed with both `go generate ./...` and `accessory -type Subject -receiver s -output subject_accessor.go ./internal/collections/domain/collection/`

https://github.com/trim21/server/blob/5bca329521b6648490cca6deacd10a4cd6d7d5be/internal/collections/domain/collection/subject.go#L53

I'm sure my source files are compilable, it pass both `go build ./...` and `go test ./... -run=nope`.

But I'm using go118 generic, do it matter?

**Comment by masaushi** [comment]
Thank you for reporting an issue! I'll try to figure out what caused it.

**Comment by masaushi** [comment]
@trim21 
The cause was probably because the go version in accessory was old.
Fixed the bug and released new version v0.0.8, so please try the latest version!
