### ISSUE TITLE
Panic after update to 3.1

### ISSUE THREAD

**Issue by evenremy** [masaushi/accessory#83]
Hi,
We got a panic from here https://github.com/masaushi/accessory/commit/efbab311d10f5a54caef842b3f0ce1745eaa61ce#diff-15aee1e466c27c175b11ff14f9d483964ea4173220060cb403c77b57d3d9ffe1R250-R255
slices.IndexFunc is returning -1 causing the panic.

**Comment by masaushi** [comment]
Thank you for reporting this! It’s a bug, so it will be fixed in the next version.

**Comment by masaushi** [comment]
"I fixed the bug and released a new version, v0.3.2 👍
